package isse.ui;

import java.util.Observable;
import java.util.Observer;

import isse.control.ControlAction;
import isse.control.Controller;
import isse.model.FieldState;
import isse.model.GameBoard;
import isse.model.GameEngine;
import isse.model.Move;
import isse.model.PlayStrategy;
import isse.model.Player;
import isse.model.strategies.DelayedPlayStrategy;
import isse.model.strategies.InteractiveUIStrategy;
import isse.model.strategies.StrategyProvider;

import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author isse-soas
 */
public class TicTacToeUI extends javax.swing.JFrame implements Observer {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2018023393038454856L;
	private JButton[][] fields;
	public Move strategySyncMove;
	private boolean delay = true; // delay for better observation
	private int delayInMs = 1000;

	public void report(int row, int column, JButton button) {
		button.setEnabled(false);
		synchronized (strategySyncMove) {
			strategySyncMove.col = column;
			strategySyncMove.row = row;
			strategySyncMove.notifyAll();
		}
	}

	/**
	 * Gets notifications from the model
	 */
	@Override
	public void update(Observable o, Object arg) {
		if (arg instanceof GameBoard) {
			// update from board
			GameBoard board = (GameBoard) arg;
			for (int i = 0; i < fields.length; ++i) {
				for (int j = 0; j < fields.length; ++j) {
					fields[i][j].setText(board.read(i, j).toString());
					if (board.read(i, j) != FieldState.EMPTY)
						fields[i][j].setEnabled(false); // could have been
														// chosen by CPU
				}
			}
		} else if (arg instanceof String) {
			String message = (String) arg;
			announcement.setText(message);
		} else if (arg instanceof ControlAction) {
			ControlAction ca = (ControlAction) arg;
			GameEngine engine = (GameEngine) o;
			GameBoard board = engine.getBoard();
			switch (ca) {
			case INTERACTIVE_MODE:
				setEnabledField(board, true, false);
				break;
			case CPU_MODE:
				setEnabledField(board, false, false);
				break;
			case GAME_ENDED:
				setEnabledField(board, false, true);
				break;
			}
		}

	}

	private void setEnabledField(GameBoard board, boolean b, boolean ended) {
		for (int i = 0; i < fields.length; ++i) {
			for (int j = 0; j < fields.length; ++j) {
				if (board.read(i, j) == FieldState.EMPTY || ended)
					fields[i][j].setEnabled(b);
			}
		}
	}

	/**
	 * Creates new form NewJFrame
	 */
	public TicTacToeUI() {

		sp = new StrategyProvider();
		initComponents();
		fields = new JButton[3][3];
		fields[0][0] = field00;
		fields[0][1] = field01;
		fields[0][2] = field02;
		fields[1][0] = field10;
		fields[1][1] = field11;
		fields[1][2] = field12;
		fields[2][0] = field20;
		fields[2][1] = field21;
		fields[2][2] = field22;
		initStrategyBoxes();
	}

	private void initStrategyBoxes() {
		String[] strategyIdentifiers = sp.provideStrategyKeywords();

		player1Strategy.setModel(new javax.swing.DefaultComboBoxModel<>(
				strategyIdentifiers));
		player2Strategy.setModel(new javax.swing.DefaultComboBoxModel<>(
				strategyIdentifiers));

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		player1Strategy = new javax.swing.JComboBox<>();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		player2Strategy = new javax.swing.JComboBox<>();
		field00 = new javax.swing.JButton();
		field20 = new javax.swing.JButton();
		field10 = new javax.swing.JButton();
		field21 = new javax.swing.JButton();
		field11 = new javax.swing.JButton();
		field01 = new javax.swing.JButton();
		field22 = new javax.swing.JButton();
		field12 = new javax.swing.JButton();
		field02 = new javax.swing.JButton();
		jLabel3 = new javax.swing.JLabel();
		announcement = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		delaySlider = new javax.swing.JSlider();
		cpuDelay = new java.awt.Label();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setResizable(false);

		player1Strategy.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "Human", "CPU" }));

		jLabel1.setText("Player 1 (X)");

		jLabel2.setText("Player 2 (O)");

		player2Strategy.setModel(new javax.swing.DefaultComboBoxModel<>(
				new String[] { "Human", "CPU" }));

		field00.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
		// field00.setText("X");
		field00.setToolTipText("");
		field00.setEnabled(false);
		field00.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				field00ActionPerformed(evt);
			}
		});

		field20.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
		field20.setEnabled(false);
		field20.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				field20ActionPerformed(evt);
			}
		});

		field10.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
		field10.setEnabled(false);
		field10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				field10ActionPerformed(evt);
			}
		});

		field21.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
		field21.setEnabled(false);
		field21.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				field21ActionPerformed(evt);
			}
		});

		field11.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
		// field11.setText("O");
		field11.setEnabled(false);
		field11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				field11ActionPerformed(evt);
			}
		});

		field01.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
		field01.setEnabled(false);
		field01.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				field01ActionPerformed(evt);
			}
		});

		field22.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
		field22.setEnabled(false);
		field22.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				field22ActionPerformed(evt);
			}
		});

		field12.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
		field12.setEnabled(false);
		field12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				field12ActionPerformed(evt);
			}
		});

		field02.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
		field02.setEnabled(false);
		field02.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				field02ActionPerformed(evt);
			}
		});

		jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
		jLabel3.setText("Tic-Tac-Toe @ ISSE/SOAS");

		announcement.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
		announcement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		announcement.setText("Welcome to the Game");
		announcement.setName(""); // NOI18N

		jButton1.setText("Start");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup().addGap(120, 120, 120)
								.addComponent(jLabel3).addGap(142, 142, 142))
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(146,
																		146,
																		146)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						field20,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						80,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						field00,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						80,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						field10,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						80,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						field21,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						80,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						field01,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						80,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						field11,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						80,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						field22,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						80,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						field02,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						80,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						field12,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						80,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGap(232,
																										232,
																										232)
																								.addComponent(
																										jButton1,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										80,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addContainerGap()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING,
																												false)
																												.addComponent(
																														jLabel1,
																														javax.swing.GroupLayout.Alignment.LEADING,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														Short.MAX_VALUE)
																												.addComponent(
																														player1Strategy,
																														javax.swing.GroupLayout.Alignment.LEADING,
																														javax.swing.GroupLayout.PREFERRED_SIZE,
																														javax.swing.GroupLayout.DEFAULT_SIZE,
																														javax.swing.GroupLayout.PREFERRED_SIZE))
																								.addGap(20,
																										20,
																										20)
																								.addComponent(
																										announcement,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										294,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		Short.MAX_VALUE)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																				.addComponent(
																						jLabel2,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						player2Strategy,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.PREFERRED_SIZE))))
								.addContainerGap(159, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(32, 32, 32)
								.addComponent(jLabel3)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(
														field00,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														80,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														field01,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														80,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														field02,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														80,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										11, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		field10,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		80,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		field20,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		80,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		field11,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		80,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		field21,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		80,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		field12,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		80,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		field22,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		80,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										11, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel1)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										player1Strategy,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel2)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										player2Strategy,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.PREFERRED_SIZE)))
																.addGap(104,
																		104,
																		104))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		jButton1)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		announcement,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		63,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(47, 47,
																		47)))));

		pack();
	}// </editor-fold>

	private void field00ActionPerformed(java.awt.event.ActionEvent evt) {
		report(0, 0, field00);
	}

	private void field20ActionPerformed(java.awt.event.ActionEvent evt) {
		report(2, 0, field20);
	}

	private void field10ActionPerformed(java.awt.event.ActionEvent evt) {
		report(1, 0, field10);
	}

	private void field21ActionPerformed(java.awt.event.ActionEvent evt) {
		report(2, 1, field21);
	}

	private void field11ActionPerformed(java.awt.event.ActionEvent evt) {
		report(1, 1, field11);
	}

	private void field01ActionPerformed(java.awt.event.ActionEvent evt) {
		report(0, 1, field01);
	}

	private void field22ActionPerformed(java.awt.event.ActionEvent evt) {
		report(2, 2, field22);
	}

	private void field12ActionPerformed(java.awt.event.ActionEvent evt) {
		report(1, 2, field12);
	}

	private void field02ActionPerformed(java.awt.event.ActionEvent evt) {
		report(0, 2, field02);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		for (int i = 0; i < fields.length; ++i) {
			for (int j = 0; j < fields.length; ++j) {
				fields[i][j].setEnabled(true);
			}
		}
		player1Strategy.setEnabled(false);
		player2Strategy.setEnabled(false);
		jButton1.setEnabled(false);

		// now engine should start etc

		String firstSelection = (String) player1Strategy.getSelectedItem();
		String secondSelection = (String) player2Strategy.getSelectedItem();
		PlayStrategy first = sp.getStrategy(firstSelection);
		PlayStrategy second = sp.getStrategy(secondSelection);
		final PlayStrategy firstStrategy = delay
				&& (!(first instanceof InteractiveUIStrategy)) ? new DelayedPlayStrategy(
				first, delayInMs) : first;
		final PlayStrategy secondStrategy = delay
				&& (!(second instanceof InteractiveUIStrategy)) ? new DelayedPlayStrategy(
				second, delayInMs) : second;

		controller.startGame(firstStrategy, secondStrategy);

	}

	// Variables declaration - do not modify
	private javax.swing.JLabel announcement;
	private javax.swing.JButton field00;
	private javax.swing.JButton field01;
	private javax.swing.JButton field02;
	private javax.swing.JButton field10;
	private javax.swing.JButton field11;
	private javax.swing.JButton field12;
	private javax.swing.JButton field20;
	private javax.swing.JButton field21;
	private javax.swing.JButton field22;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JComboBox<String> player1Strategy;
	private javax.swing.JComboBox<String> player2Strategy;
	private java.awt.Label cpuDelay;
	private javax.swing.JSlider delaySlider;
	// End of variables declaration
	private StrategyProvider sp;
	private Controller controller;

	public void setController(Controller controller) {
		this.controller = controller;

	}
}
